[package]
name = "account"
authors = ["Kianoush Dortaj <kiadr9372@gmail.com>"]
edition = "2021"
homepage = "https://moonbeam.network"
license = "GPL-3.0-only"
repository = "https://github.com/paritytech/substrate/"
version = "0.1.1"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
blake2-rfc = { version = "0.2.18", default-features = false }
impl-serde = { version = "0.4.0", default-features = false }
libsecp256k1 = { version = "0.7", default-features = false, eatures = ["hmac"] }
log = { version = "0.4", default-features = false }
serde = { version = "1.0.101", default-features = false, features = ["derive"] }
sha3 = { version = "0.10", default-features = false }

# Substrate


[dev-dependencies]
hex = { version = "0.4.3", default-features = false }

[features]
default = ["std"]
std = [
	"hex/std",
	"impl-serde/std",
	"libsecp256k1/std",
	"serde/std",
	"sha3/std",
]